apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: ansible-proxy
    title: Ansible Proxy Role
    description: Role for Ansible which configures the proxy client parameters in RHEL systems
    namespace: stone
    tags:
      - iac-library
      - ansible
    annotations:
      legacy.stone.tech/owner-email: foundation.platform@stone.com.br
spec:
    type: library
    lifecycle: production
    owner: stone-payments/foundation-platform
