---
- name: adds registry keys to configure proxy polices
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: ProxySettingsPerUser
    type: dword
    data: 0
    state: present

- name: adds registry keys to configure proxy
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    data: "{{ item.data }}"
    state: present
  with_items:
    - { name: ProxyEnable, type: dword, data: 1 }
    - { name: ProxyServer, type: string, data: "{{ proxy_address }}:{{ proxy_port }}" }
    - { name: ProxyOverride, type: multistring, data: "{{ proxy_bypass + ['<local>'] }}" }

- name: configures proxy using xProxySettings DSC Resource
  win_dsc:
    resource_name: xProxySettings
    IsSingleInstance: 'Yes'
    Ensure: Present
    EnableAutoDetection: false
    EnableAutoConfiguration: false
    EnableManualProxy: true
    ProxyServer: "{{ proxy_address }}:{{ proxy_port }}"
    ProxyServerExceptions: "{{ proxy_bypass }}"
    ProxyServerBypassLocal: true
