---
- name: Task block to configure Windows INet which includes Internet Explorer
  block:
    - name: Enforce uniform proxy settings for all user accounts
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
        name: ProxySettingsPerUser
        type: dword
        data: 0
        state: present

    - name: Configure legacy applications to use the system proxy
      win_regedit:
        path: HKLM:\SOFTWARE{{ item.0 }}\Microsoft\Windows\CurrentVersion\Internet Settings
        name: "{{ item.1.name }}"
        type: "{{ item.1.type }}"
        data: "{{ item.1.data }}"
        state: present
      with_nested:
        - - ""
          - \WOW6432Node
        - - name: ProxyEnable
            type: dword
            data: 1
          - name: ProxyServer
            type: string
            data: "{{ 'socks=' if ('socks' in proxy_proto) else '' }}{{ proxy_address }}:{{ proxy_port }}"
          - name: ProxyOverride
            type: string
            data: "{{ (proxy_whitelist + ['<local>']) | join(';') }}"

    - name: Configure updated applications to use the system proxy
      win_inet_proxy:
        proxy: "{{ 'socks=' if ('socks' in proxy_proto) else '' }}{{ proxy_address }}:{{ proxy_port }}"
        bypass: "{{ (proxy_whitelist + ['<local>']) }}"
  when: proxy_win_inet

- name: Set a proxy using Windows HTTP Services (WinHTTP) with a specific port with a bypass list
  win_http_proxy:
    proxy: "{{ 'socks=' if ('socks' in proxy_proto) else '' }}{{ proxy_address }}:{{ proxy_port }}"
    bypass: "{{ (proxy_whitelist + ['<local>']) }}"
  when: proxy_win_http
