---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: windows2016
    box: sysnet4admin/Windows2016
    memory: 2048
    cpus: 2
    provider_options:
      gui: false
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        proxy_address: "example.com"
        proxy_port: 3128
        proxy_whitelist:
          - ".google.com"
          - ".stone.com"
  connection_options:
    ansible_connection: winrm
    ansible_host: 127.0.0.1
    ansible_port: 55985
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_winrm_transport: ntlm
    ansible_winrm_scheme: http
scenario:
  name: windows
verifier:
  name: testinfra
  lint:
    name: flake8
