---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: removes old xNetworking resource
      win_psmodule:
        name: xNetworking
        state: absent
        become_method: runas

    - name: install new xNetworking resource
      win_psmodule:
        name: xNetworking
        repository: PSGallery
        allow_clobber: true
        state: present
        become_method: runas
