---
- name: Task block to disable proxy
  block:
    - name: Configure yum to not use the proxy
      lineinfile:
        path: "/etc/yum.conf"
        regexp: '^proxy\s*=.*'
        state: absent

    - name: Configure RHSM to not use the proxy
      lineinfile:
        path: "/etc/rhsm/rhsm.conf"
        regexp: "{{ item.regexp }}"
        state: absent
      with_items:
        - regexp: '^proxy_hostname\s*=.*'
        - regexp: '^proxy_port\s*=.*'
      when: ansible_distribution == "RedHat"

    - name: Configure yum to not use proxy authentication
      lineinfile:
        path: "/etc/yum.conf"
        regexp: "{{ item.regexp }}"
        state: absent
      with_items:
        - regexp: '^proxy_username\s*=.*'
        - regexp: '^proxy_password\s*=.*'

    - name: Configure RHSM to not use the proxy authentication
      lineinfile:
        path: "/etc/rhsm/rhsm.conf"
        regexp: "{{ item.regexp }}"
        state: absent
      with_items:
        - regexp: '^proxy_user\s*=.*'
        - regexp: '^proxy_password\s*=.*'
      when: ansible_distribution == "RedHat"
  when: proxy_redhat

- name: Configure the default profile to not use a proxy
  file:
    path: "/etc/profile.d/proxy.sh"
    state: absent
  register: proxy_profile_result

- name: Ensure that sudo not use the proxy
  blockinfile:
    path: /etc/sudoers
    insertafter: '(^Defaults\s+env_keep)'
    block: |
      Defaults    env_keep += "ftp_proxy http_proxy https_proxy no_proxy"
    marker: "# {mark} - Ansible managed block - Ensure that sudo use the proxy"
    state: absent
    validate: /usr/sbin/visudo -cf %s
  register: proxy_sudo_result
  when: proxy_sudo | bool

- name: Force reload gathered facts
  block:
    - name: Clear gathered facts from all currently targeted hosts
      meta: clear_facts

    - name: Force collect ansible_env facts to unload http_proxy environment variable
      setup:
  when: (proxy_profile_result is changed) or (proxy_sudo_result is changed)

- name: Task block to disable proxy on SystemD
  block:
    - name: Configure the systemd to use the proxy
      template:
        src: proxy.conf.j2
        dest: /etc/systemd/system.conf.d/proxy.conf
        state: absent
      register: proxy_systemd_result

    - name: Configure the systemd to use the proxy at runtime
      command: systemctl unset-environment {{ item }}
      loop:
        - proxy
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
        - no_proxy
        - NO_PROXY
      when: proxy_systemd_result is changed
      notify: Reload systemd

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers
  when: proxy_systemd | bool
