---
- include: enable.yml
  when: proxy_address != "" and proxy_port != ""
  tags:
    - proxy
    - proxy_enable

- include: disable.yml
  when: proxy_address == "" or proxy_port == ""
  tags:
    - proxy
    - proxy_disable
